import { useRouter } from "next/router";
import Head from "next/head";

const DynamicName = () => {
    const router = useRouter();
  console.log("");
  return (
    <div className="div">
      {" "}
      <Head>
        <title>{router.query.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div> this is dynamic page {router.query.name}</div>
    </div>
  );
};

export default DynamicName;