import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useRouter} from 'next/router'

// components
import Banner from './components/banner.jsx'

export default function Home() {

  const router = useRouter();
  console.log('this is router in home page', router)
   const handleOnBannerBtnClick = () => {
     console.log("banner button is clicked");
   };
  return (
    <div className={styles.container}>
      <Head>
        <title>{router.query.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText={"find nearby cafe"}
          handleOnClick={handleOnBannerBtnClick}
        />

        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            width={700}
            height={400}
            alt="image here"
          />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Built by <span className={styles.logo}>Angelo</span>
        </a>
      </footer>
    </div>
  );
}
